const ROLES_ACTION_TYPES = {
  // Get Roles
  ROLES_DATA_REQUEST: "ROLES_DATA_REQUEST",
  ROLES_DATA_SUCCESS: "ROLES_DATA_SUCCESS",
  ROLES_DATA_FAILURE: "ROLES_DATA_FAILURE",

  // Access Control
  ACCESS_CONTROl_REQUEST: "ACCESS_CONTROl_REQUEST",
  ACCESS_CONTROl_SUCCESS: "ACCESS_CONTROl_SUCCESS",
  ACCESS_CONTROl_FAILURE: "ACCESS_CONTROl_FAILURE",
};

export default ROLES_ACTION_TYPES;
